version: "3.9"
services:
  q-redis:  
    image: redis:6.2.6
    ports:
      - "6379:6379"
  q-nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/logs
      - ../backend/images:/www/data:ro
  q-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=quantom
      - POSTGRES_DB=event